#!/bin/bash

# LANA-AI WireGuard VPN Setup Script
# Installs and configures WireGuard server on macOS

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default configuration
WG_INTERFACE="wg0"
WG_PORT="51820"
WG_SERVER_IP="10.100.0.1/24"
WG_SUBNET="10.100.0.0/24"
WG_CONFIG_DIR="/usr/local/etc/wireguard"
WG_CONFIG_FILE="$WG_CONFIG_DIR/$WG_INTERFACE.conf"

# Function to print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Homebrew is installed
check_homebrew() {
    if ! command -v brew &> /dev/null; then
        print_error "Homebrew is not installed. Install it from https://brew.sh"
        exit 1
    fi
    print_info "Homebrew found"
}

# Install WireGuard (as regular user, not root)
install_wireguard() {
    print_info "Checking WireGuard installation..."

    if command -v wg &> /dev/null; then
        print_info "WireGuard is already installed"
        wg --version
        return 0
    fi

    # Check if running as root - can't install via Homebrew
    if [ "$EUID" -eq 0 ]; then
        print_error "Cannot install WireGuard via Homebrew as root"
        print_error "Please run this command first as a regular user:"
        print_error "  brew install wireguard-tools"
        print_error "Then re-run this script with sudo"
        exit 1
    fi

    print_info "Installing WireGuard via Homebrew..."
    brew install wireguard-tools

    if ! command -v wg &> /dev/null; then
        print_error "WireGuard installation failed"
        exit 1
    fi

    print_info "WireGuard installed successfully"
    wg --version
}

# Generate server keys (requires root for /usr/local/etc/wireguard)
generate_server_keys() {
    print_info "Generating WireGuard server keys..."

    # Check if root is needed
    if [ ! -d "$WG_CONFIG_DIR" ]; then
        if [ "$EUID" -ne 0 ]; then
            print_error "Root privileges required to create $WG_CONFIG_DIR"
            print_error "Please run this script with sudo"
            exit 1
        fi
    fi

    # Create config directory
    mkdir -p "$WG_CONFIG_DIR"
    chmod 700 "$WG_CONFIG_DIR"

    # Generate private and public keys
    local PRIVATE_KEY_FILE="$WG_CONFIG_DIR/server_private.key"
    local PUBLIC_KEY_FILE="$WG_CONFIG_DIR/server_public.key"

    if [ -f "$PRIVATE_KEY_FILE" ]; then
        print_warn "Server keys already exist. Reusing existing keys to maintain compatibility."
        print_info "  Private key: $PRIVATE_KEY_FILE"
        print_info "  Public key: $PUBLIC_KEY_FILE"
        echo
        print_info "Server public key: $(cat $PUBLIC_KEY_FILE)"
        echo
        print_info "Existing keys preserved - all registered devices remain valid"
        return 0
    fi

    wg genkey | tee "$PRIVATE_KEY_FILE" | wg pubkey > "$PUBLIC_KEY_FILE"
    chmod 600 "$PRIVATE_KEY_FILE"
    chmod 644 "$PUBLIC_KEY_FILE"

    print_info "Server keys generated:"
    print_info "  Private key: $PRIVATE_KEY_FILE"
    print_info "  Public key: $PUBLIC_KEY_FILE"
    echo
    print_info "Server public key: $(cat $PUBLIC_KEY_FILE)"
}

# Generate bootstrap pre-shared key
generate_bootstrap_psk() {
    print_info "Generating bootstrap pre-shared key..."

    local BOOTSTRAP_PSK_FILE="$WG_CONFIG_DIR/bootstrap.psk"

    if [ -f "$BOOTSTRAP_PSK_FILE" ]; then
        print_warn "Bootstrap PSK already exists. Reusing existing PSK to maintain compatibility."
        print_info "Bootstrap PSK: $(cat $BOOTSTRAP_PSK_FILE)"
        echo
        print_info "Existing PSK preserved - all registered devices remain valid"
        return 0
    fi

    # Generate PSK using wg or openssl
    if command -v wg &> /dev/null; then
        wg genpsk > "$BOOTSTRAP_PSK_FILE"
    else
        # Fallback to openssl if wg command not available yet
        openssl rand -base64 32 > "$BOOTSTRAP_PSK_FILE"
    fi

    chmod 600 "$BOOTSTRAP_PSK_FILE"

    print_info "Bootstrap PSK generated: $BOOTSTRAP_PSK_FILE"
    print_info "Bootstrap PSK: $(cat $BOOTSTRAP_PSK_FILE)"
    echo
    print_warn "This PSK allows initial VPN connections before device registration."
    print_warn "Keep it secure and add it to the hosted discovery service."
}

# Create server configuration
create_server_config() {
    print_info "Creating WireGuard server configuration..."

    local PRIVATE_KEY=$(cat "$WG_CONFIG_DIR/server_private.key")

    if [ -f "$WG_CONFIG_FILE" ]; then
        print_warn "Config file already exists. Backing up to ${WG_CONFIG_FILE}.backup"
        cp "$WG_CONFIG_FILE" "${WG_CONFIG_FILE}.backup"
    fi

    cat > "$WG_CONFIG_FILE" <<EOF
# WireGuard Server Configuration
# Generated by LANA-AI setup script
# $(date)

[Interface]
Address = $WG_SERVER_IP
ListenPort = $WG_PORT
PrivateKey = $PRIVATE_KEY

# Enable IP forwarding (uncomment after configuring system)
# PostUp = sysctl -w net.inet.ip.forwarding=1
# PostDown = sysctl -w net.inet.ip.forwarding=0

# Peers will be added by the LANA-AI VPN service
# Do not manually edit peer configurations below this line
# Use the /api/v1/vpn endpoints to manage peers

EOF

    chmod 600 "$WG_CONFIG_FILE"
    print_info "Server config created: $WG_CONFIG_FILE"
}

# Enable IP forwarding
enable_ip_forwarding() {
    print_info "Configuring IP forwarding..."

    # Check current setting
    local current=$(sysctl -n net.inet.ip.forwarding)
    print_info "Current IP forwarding setting: $current"

    if [ "$current" = "1" ]; then
        print_info "IP forwarding is already enabled"
        return 0
    fi

    print_warn "IP forwarding is disabled. Enable it? (y/n)"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        sysctl -w net.inet.ip.forwarding=1
        print_info "IP forwarding enabled"
        print_warn "Note: This setting is temporary and will reset on reboot"
        print_warn "To make it permanent, add 'net.inet.ip.forwarding=1' to /etc/sysctl.conf"
    else
        print_warn "Skipping IP forwarding configuration"
    fi
}

# Create .env configuration
update_env_file() {
    print_info "Updating .env file with VPN configuration..."

    local ENV_FILE="/Users/redroostertechnologies/Desktop/LANA-AI/.env"
    local PUBLIC_KEY=$(cat "$WG_CONFIG_DIR/server_public.key")

    if [ ! -f "$ENV_FILE" ]; then
        print_warn ".env file not found. Skipping .env update."
        print_info "If running from deploy-prod-mac.sh, this is expected."
        print_info "If running standalone, please create .env first or run deploy-prod-mac.sh"
        return 0
    fi

    # Backup .env
    cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"

    # Add or update VPN configuration
    if grep -q "^VPN_ENABLED=" "$ENV_FILE"; then
        print_info "Updating existing VPN configuration in .env"
    else
        print_info "Adding VPN configuration to .env"
        cat >> "$ENV_FILE" <<EOF

# WireGuard VPN Configuration
VPN_ENABLED=false
WIREGUARD_ENABLED=false
WIREGUARD_INTERFACE=$WG_INTERFACE
WIREGUARD_PORT=$WG_PORT
WIREGUARD_SERVER_ADDRESS=$WG_SERVER_IP
WIREGUARD_SUBNET=$WG_SUBNET
WIREGUARD_DNS=10.100.0.1
WIREGUARD_PUBLIC_ENDPOINT=
WIREGUARD_SERVER_PRIVATE_KEY_PATH=$WG_CONFIG_DIR/server_private.key
WIREGUARD_SERVER_PUBLIC_KEY_PATH=$WG_CONFIG_DIR/server_public.key
WIREGUARD_CONFIG_PATH=$WG_CONFIG_FILE
WIREGUARD_CLIENT_CONFIG_DIR=$WG_CONFIG_DIR/clients
WIREGUARD_CLIENT_IP_START=10.100.0.10
WIREGUARD_CLIENT_IP_END=10.100.0.254
WIREGUARD_KEEPALIVE=25
VPN_ENCRYPTION_KEY=$(openssl rand -hex 32)
EOF
    fi

    print_info ".env file updated"
}

# Print next steps
print_next_steps() {
    echo
    print_info "=========================================="
    print_info "WireGuard Setup Complete!"
    print_info "=========================================="
    echo
    print_info "Next steps:"
    echo
    echo "1. Configure your public endpoint in .env:"
    echo "   WIREGUARD_PUBLIC_ENDPOINT=<your-public-ip>:$WG_PORT"
    echo
    echo "2. Enable VPN in .env:"
    echo "   VPN_ENABLED=true"
    echo "   WIREGUARD_ENABLED=true"
    echo
    echo "3. Configure firewall to allow UDP port $WG_PORT:"
    echo "   sudo pfctl -e"
    echo "   sudo pfctl -f /etc/pf.conf"
    echo
    echo "4. Start WireGuard interface:"
    echo "   sudo wg-quick up $WG_INTERFACE"
    echo
    echo "5. Restart LANA-AI Chef server to load VPN configuration"
    echo
    echo "6. Users can download their VPN configs from:"
    echo "   https://<your-server>/api/v1/vpn/client-config"
    echo
    print_info "Server Public Key:"
    cat "$WG_CONFIG_DIR/server_public.key"
    echo
}

# Main installation flow
main() {
    echo
    print_info "=========================================="
    print_info "LANA-AI WireGuard VPN Setup"
    print_info "=========================================="
    echo

    check_homebrew
    install_wireguard
    generate_server_keys
    generate_bootstrap_psk
    create_server_config
    enable_ip_forwarding
    update_env_file
    print_next_steps
}

# Run main function
main
