(function () {
  'use strict';

  window.LanaInsightsDashboards = [
    {
      key: 'owner',
      name: 'Owner Performance',
      description: 'Financial performance, cash flow, revenue goals, owner benefit, and bonus compensation.',
      audience: 'Owner',
      category: 'Finance',
      scope: 'Organization-wide',
      visibility: 'Owner only',
      state: 'Active',
      tags: 'Finance, goals, cash flow',
      href: 'admin/dashboard-detail.html?type=owner',
      usageRank: 1,
      recentRank: 2,
    },
    {
      key: 'department',
      name: 'Department Dashboards',
      description: 'Marketing, Sales & Intake, and Legal Department metrics grouped for management visibility.',
      audience: 'Management',
      category: 'Operations',
      scope: 'Department groups',
      visibility: 'Role-based',
      state: 'Active',
      tags: 'Marketing, intake, legal',
      href: 'admin/dashboard-detail.html?type=department',
      usageRank: 2,
      recentRank: 1,
    },
    {
      key: 'attorney',
      name: 'Attorney Performance',
      description: 'Attorney-level trust C&D meetings, owner-set targets, bonus calculations, and payment month.',
      audience: 'Attorney',
      category: 'Compensation',
      scope: 'Individual user',
      visibility: 'Assigned attorney',
      state: 'Active',
      tags: 'Targets, ACV, bonus',
      href: 'admin/dashboard-detail.html?type=attorney',
      usageRank: 3,
      recentRank: 3,
    },
    {
      key: 'other',
      name: 'Additional Dashboards',
      description: 'Legacy maintenance, funding, guardianship, probate, Medicaid, and future dashboard groups.',
      audience: 'Mixed',
      category: 'Legal services',
      scope: 'Configurable',
      visibility: 'Resource shares',
      state: 'Active',
      tags: 'Legal services, maintenance',
      href: 'admin/dashboard-detail.html?type=other',
      usageRank: 4,
      recentRank: 4,
    },
  ];
})();
